---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

<!-- You'll still need to render `README.Rmd` regularly, to keep `README.md` up-to-date. `devtools::build_readme()` is handy for this.  -->



```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# Insert Package Name

<!-- badges: start -->
<!-- badges: end -->

The goal of XXX is to ...

## Installation

The development version of XXX is available from [GitHub](https://github.com/) with:

``` {r}
# install.packages("devtools")
devtools::install_github("Reed-Math241/pkgDemo")
```

```{r}
install.packages("devtools")
devtools::install()
```

```{r}
devtools::build_readme()

#path = "~/math241/project 1/pkgGrpm"
```

```{r}
#usethis::use_data_raw()
```

```{r}
#usethis::use_data(weed, overwrite = TRUE)
```

```{r}
#usethis::use_r("weed.rda")
#devtools::document()
```



```{r}
#devtools::check(document = FALSE)
```

```{r}
#devtools::load_all()
```

```{r}
#devtools::install("pkggrpm")
```
## About the data 

The Data were collected and made available by the City of Denver Open Data Catalog

It contains the dataswe `weed`, which contains 4 variables and 90 observations.

```{r}
library(pkgGrpm)

head(weed)
```


## Example

```{r}

library(pkgGrpm)

head(weed)

```

```{r example}
library(pkgGrpm)
```




